require("mohit.core.colorscheme")
require("mohit.core.options")
require("mohit.core.keymaps")
require("mohit.plugins-setup")
require("mohit.plugins.comment")
require("mohit.plugins.nvim-tree")
require("mohit.plugins.nvim-cmp")
require("mohit.plugins.lsp.mason")
require("mohit.plugins.lsp.lspsaga")
require("mohit.plugins.lsp.lspconfig")
require("mohit.plugins.lsp.null-ls")
require("mohit.plugins.autopairs")
require("mohit.plugins.treesitter")
require("mohit.plugins.bufferline")
require("mohit.plugins.toggle-term")

